language: python
python:
  - "3.6"
services:
  - docker
script:
  - exec ./scripts/test.sh
jobs:
  include:
    - env:
        - NEO4J_VERSION=3.5-enterprise
        - POSTGRES_VERSION=10
    - env:
        - NEO4J_VERSION=3.5-enterprise
        - POSTGRES_VERSION=11
    - env:
        - NEO4J_VERSION=3.5-enterprise
        - POSTGRES_VERSION=12
    - env:
        - NEO4J_VERSION=4.1-enterprise
        - POSTGRES_VERSION=10
    - env:
        - NEO4J_VERSION=4.1-enterprise
        - POSTGRES_VERSION=11
    - env:
        - NEO4J_VERSION=4.1-enterprise
        - POSTGRES_VERSION=12
